app.name: tbk-bitcoin-fee-demo
app.description: A spring boot bitcoin demo application

spring.application.name: 'tbk-bitcoin-fee-demo'
spring.http.log-request-details: false

server.port: 8080
server.compression.enabled: true

management.server.port: 9001

# LOGGING
logging.file.name: application.log
logging.config: classpath:logback.xml
logging.level.org.springframework: INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
#logging.level.web: DEBUG

# logging.level.org.tbk.bitcoin: DEBUG

# enable or disable fee providers taking part in fee recommendations.
# as most fee providers are included in this example application,
# be aware that some providers will skew the result with rather low quality estimations.
#org.tbk.bitcoin.tool.fee.bitcoinerlive.enabled: false
#org.tbk.bitcoin.tool.fee.bitcore.enabled: false
#org.tbk.bitcoin.tool.fee.bitgo.enabled: false
#org.tbk.bitcoin.tool.fee.blockchaininfo.enabled: false
#org.tbk.bitcoin.tool.fee.blockchair.enabled: false
#org.tbk.bitcoin.tool.fee.blockcypher.enabled: true
#org.tbk.bitcoin.tool.fee.blockstreaminfo.enabled: false
org.tbk.bitcoin.tool.fee.btcdotcom.enabled: false # disabled as it gives rather bad quality estimates (on 2021-05-27)
org.tbk.bitcoin.tool.fee.earndotcom.enabled: false # disabled as it returns errors consistently (on 2021-05-27)
