
org.tbk.spring.testcontainer.bitcoind:
  enabled: true
  rpcuser: myrpcuser
  rpcpassword: correcthorsebatterystaple
  commands:
    # [debug]
    # Enable debug logging for categories.
    # '-debug=1' would log ALL messages
    - '-debug=rpc'
    # Log transaction fee per kB when mining blocks.
    - '-printpriority=1'

org.tbk.bitcoin.jsonrpc:
  network: regtest
  rpchost: http://localhost
  rpcport: 18443
  rpcuser: myrpcuser
  rpcpassword: correcthorsebatterystaple
